In [1]:
import numpy as np

# Enable pretty printing
np.set_printoptions(precision=3, suppress=True)

In [2]:
from chromalab.screening import ScreeningTest
from chromalab.observer import Observer, Cone, getSampledHyperCube

In [3]:
%load_ext autoreload
%autoreload 2
%matplotlib ipympl

In [4]:
wavelengths = np.arange(400, 700, 1)
MandLPeaks = np.array([(530, 559), (530, 555), (533, 559), (533, 555)])
observers = [Observer.tetrachromat(wavelengths), Observer.neitz_tetrachromat(wavelengths), Observer.govardovskii_tetrachromat(wavelengths)]

In [5]:
all_steps = np.arange(0, 256)/255

In [6]:
st = ScreeningTest("neitz_common_genes", wavelengths, MandLPeaks, noise_range=[0, 0.05, 0.1], hypercube_sample=0.02)
st.create_observers_vs_noise()
print(st.metamers_per_observer)
print(st.plate_numbers)

Generating hypercube
Done generating hypercube


 25%|██▌       | 1/4 [00:11<00:33, 11.06s/it]

[[ 0.434  0.23   0.27   0.32 ]
 [ 0.431  0.234  0.295  0.325]]


 50%|█████     | 2/4 [00:21<00:21, 10.72s/it]

[[ 0.443  0.341  0.429  0.476]
 [ 0.441  0.345  0.445  0.479]]


 75%|███████▌  | 3/4 [00:32<00:10, 10.67s/it]

[[ 0.427  0.346  0.415  0.48 ]
 [ 0.428  0.349  0.435  0.484]]


100%|██████████| 4/4 [00:42<00:00, 10.64s/it]

[[ 0.433  0.34   0.41   0.455]
 [ 0.433  0.344  0.425  0.46 ]]


[array([[ 0.96,  0.  ,  0.  ,  0.32,  1.  ,  0.86],
       [ 0.08,  0.  ,  0.  ,  0.62,  0.42,  1.  ]]), array([[ 0.96,  0.  ,  0.  ,  0.72,  1.  ,  0.88],
       [ 0.06,  0.  ,  0.  ,  0.98,  0.52,  1.  ]]), array([[ 0.86,  0.  ,  0.  ,  0.7 ,  1.  ,  0.84],
       [ 0.08,  0.  ,  0.  ,  0.98,  0.38,  1.  ]]), array([[ 0.94,  0.  ,  0.  ,  0.68,  0.98,  0.86],
       [ 0.1 ,  0.  ,  0.  ,  0.94,  0.44,  1.  ]])]
[64 67 35 87 68 89 85 64 85 27 68 35]


In [7]:
st = ScreeningTest("govardovskii_common_genes", wavelengths, MandLPeaks, noise_range=[0, 0.05, 0.1], hypercube_sample=0.02, template='govardovskii')
st.create_observers_vs_noise()
print(st.metamers_per_observer)
print(st.plate_numbers)

Generating hypercube
Done generating hypercube


 25%|██▌       | 1/4 [00:10<00:32, 10.72s/it]

[[ 0.4    0.151  0.16   0.2  ]
 [ 0.405  0.155  0.19   0.205]]


In [ ]:
st = ScreeningTest("stockman_vs_neitz_vs_govardovskii", wavelengths, observers=observers, noise_range=[0, 0.05, 0.1], hypercube_sample=0.02)
st.create_observers_vs_noise()

print(st.metamers_per_observer)
print(st.plate_numbers)

In [ ]:
st = ScreeningTest("neitz_common_genes_rdmclr", wavelengths, MandLPeaks, noise_range=[0, 0.05, 0.1], hypercube_sample=0.02, randomIndex=True)
st.create_observers_vs_noise()
print(st.metamers_per_observer)
print(st.plate_numbers)

In [ ]:
(np.array([[ 0.9 ,  0.  ,  0.  ,  0.04,  0.7 ,  0.12],
       [ 0.2 ,  0.  ,  0.  ,  0.28,  0.18,  0.24]]) * 255).astype(int)

In [ ]:
A = (np.array([[ 0.96,  0.  ,  0.  ,  0.78,  0.58,  0.6 ],
       [ 0.38,  0.  ,  0.  ,  0.98,  0.18,  0.68]]) * 255).astype(np.uint8)
B = (np.array([[ 0.98,  0.  ,  0.  ,  0.6 ,  0.74,  0.94],
       [ 0.44,  0.  ,  0.  ,  0.76,  0.44,  1.  ]]) * 255).astype(np.uint8)
C = (np.array([[ 0.96,  0.  ,  0.  ,  0.6 ,  0.88,  0.12],
       [ 0.04,  0.  ,  0.  ,  0.92,  0.12,  0.28]]) * 255).astype(np.uint8)
D = (np.array([[ 0.68,  0.  ,  0.  ,  0.36,  1.  ,  0.82],
       [ 0.3 ,  0.  ,  0.  ,  0.48,  0.74,  0.88]]) * 255).astype(np.uint8)

A, B , C, D

In [8]:
from PIL import Image

# Open an image file
image_path = './neitz_common_genes_rdmclr/neitz_common_genes_rdmclr-ocv.png'
image = Image.open(image_path)
A = np.asarray(image)
A

In [ ]:
st = ScreeningTest("govardovskii_common_genes_rdmclr", wavelengths, MandLPeaks, noise_range=[0, 0.05, 0.1], hypercube_sample=0.02, template='govardovskii', randomIndex=True)
st.create_observers_vs_noise()
print(st.metamers_per_observer)
print(st.plate_numbers)

In [ ]:
st = ScreeningTest("stockman_vs_neitz_vs_govardovskii_rdmclr", wavelengths, observers=observers, noise_range=[0, 0.05, 0.1], hypercube_sample=0.02, randomIndex=True)
st.create_observers_vs_noise()

print(st.metamers_per_observer)
print(st.plate_numbers)