In [1]:
import numpy as np

# Enable pretty printing
np.set_printoptions(precision=3, suppress=True)

In [2]:
from chromalab.screening import ScreeningTest
from chromalab.observer import Observer, Cone, getSampledHyperCube

In [3]:
%load_ext autoreload
%autoreload 2
%matplotlib ipympl

In [4]:
wavelengths = np.arange(400, 700, 1)
MandLPeaks = np.array([(530, 559), (530, 555), (533, 559), (533, 555)])
observers = [Observer.tetrachromat(wavelengths), Observer.neitz_tetrachromat(wavelengths), Observer.govardovskii_tetrachromat(wavelengths)]

In [5]:
all_steps = np.arange(0, 256)/255

In [8]:
st = ScreeningTest("neitz_common_genes", wavelengths, MandLPeaks, noise_range=[0, 0.05, 0.1], hypercube_sample=0.02)
st.create_observers_vs_noise()

print("Weights per Pair of Metamers")
print((np.array(st.metamers_per_observer)* 255).astype(np.uint8))

print(st.plate_numbers)

Generating hypercube
Done generating hypercube


 25%|██▌       | 1/4 [00:09<00:27,  9.13s/it]

Finetuned Metamers
 [[ 0.132  0.19   0.188  0.183]
 [ 0.132  0.19   0.189  0.183]]
LED Weights
 [[ 0.676  0.895  0.978  0.915]
 [ 0.726  0.883  0.915  0.958]]


 50%|█████     | 2/4 [00:17<00:17,  8.94s/it]

Finetuned Metamers
 [[ 0.129  0.199  0.194  0.189]
 [ 0.129  0.199  0.195  0.189]]
LED Weights
 [[ 0.923  0.778  0.868  0.95 ]
 [ 0.969  0.766  0.813  0.99 ]]


 75%|███████▌  | 3/4 [00:26<00:08,  8.92s/it]

Finetuned Metamers
 [[ 0.132  0.149  0.138  0.129]
 [ 0.132  0.149  0.139  0.129]]
LED Weights
 [[ 0.609  0.432  0.934  0.958]
 [ 0.655  0.42   0.88   0.998]]


100%|██████████| 4/4 [00:35<00:00,  8.94s/it]

Finetuned Metamers
 [[ 0.123  0.075  0.065  0.06 ]
 [ 0.123  0.075  0.066  0.06 ]]
LED Weights
 [[ 0.056  0.166  0.903  0.9  ]
 [ 0.169  0.134  0.758  0.997]]


Weights per Pair of Metamers
[[[  0 172   0 228 249 233]
  [  0 185   0 225 233 244]]

 [[  0 235   0 198 221 242]
  [  0 247   0 195 207 252]]

 [[  0 155   0 110 238 244]
  [  0 167   0 107 224 254]]

 [[  0  14   0  42 230 229]
  [  0  43   0  34 193 254]]]
[64 67 35 87 68 89 85 64 85 27 68 35]


In [ ]:
st = ScreeningTest("govardovskii_common_genes", wavelengths, MandLPeaks, noise_range=[0, 0.05, 0.1], hypercube_sample=0.02, template='govardovskii')
st.create_observers_vs_noise()
print(st.metamers_per_observer)
print(st.plate_numbers)

In [ ]:
st = ScreeningTest("stockman_vs_neitz_vs_govardovskii", wavelengths, observers=observers, noise_range=[0, 0.05, 0.1], hypercube_sample=0.02)
st.create_observers_vs_noise()

print(st.metamers_per_observer)
print(st.plate_numbers)

In [7]:
st = ScreeningTest("neitz_common_genes_rdmclr", wavelengths, MandLPeaks, noise_range=[0, 0.05, 0.1], hypercube_sample=0.02, randomIndex=True)
st.create_observers_vs_noise()
print("Weights per Pair of Metamers")
print((np.array(st.metamers_per_observer)* 255).astype(np.uint8))

print(st.plate_numbers)

Generating hypercube
Done generating hypercube


 25%|██▌       | 1/4 [00:08<00:26,  8.77s/it]

Finetuned Metamers
 [[ 0.139  0.199  0.19   0.18 ]
 [ 0.139  0.199  0.19   0.18 ]]
LED Weights
 [[ 0.887  0.706  0.985  0.993]
 [ 0.876  0.714  0.993  0.989]]


 50%|█████     | 2/4 [00:17<00:17,  8.87s/it]

Finetuned Metamers
 [[ 0.107  0.097  0.076  0.067]
 [ 0.107  0.097  0.076  0.067]]
LED Weights
 [[ 0.341  0.     0.962  0.648]
 [ 0.341 -0.     0.966  0.644]]


 75%|███████▌  | 3/4 [00:26<00:08,  9.00s/it]

Finetuned Metamers
 [[ 0.103  0.074  0.071  0.067]
 [ 0.103  0.074  0.071  0.067]]
LED Weights
 [[ 0.283  0.259  0.413  0.989]
 [ 0.283  0.259  0.417  0.985]]


100%|██████████| 4/4 [00:35<00:00,  8.98s/it]

Finetuned Metamers
 [[ 0.096  0.078  0.079  0.079]
 [ 0.096  0.078  0.08   0.079]]
LED Weights
 [[ 0.299  0.398  0.291  0.985]
 [ 0.311  0.398  0.271  0.993]]


Weights per Pair of Metamers
[[[  0 226   0 180 251 253]
  [  0 223   0 182 253 252]]

 [[  0  87   0   0 245 165]
  [  0  87   0   0 246 164]]

 [[  0  72   0  65 105 252]
  [  0  72   0  65 106 251]]

 [[  0  76   0 101  74 251]
  [  0  79   0 101  69 253]]]
[27 68 35 64 89 96 87 39 96 39 72 85]


In [ ]:
(np.array([[ 0.9 ,  0.  ,  0.  ,  0.04,  0.7 ,  0.12],
       [ 0.2 ,  0.  ,  0.  ,  0.28,  0.18,  0.24]]) * 255).astype(int)

In [ ]:
A = (np.array([[ 0.96,  0.  ,  0.  ,  0.78,  0.58,  0.6 ],
       [ 0.38,  0.  ,  0.  ,  0.98,  0.18,  0.68]]) * 255).astype(np.uint8)
B = (np.array([[ 0.98,  0.  ,  0.  ,  0.6 ,  0.74,  0.94],
       [ 0.44,  0.  ,  0.  ,  0.76,  0.44,  1.  ]]) * 255).astype(np.uint8)
C = (np.array([[ 0.96,  0.  ,  0.  ,  0.6 ,  0.88,  0.12],
       [ 0.04,  0.  ,  0.  ,  0.92,  0.12,  0.28]]) * 255).astype(np.uint8)
D = (np.array([[ 0.68,  0.  ,  0.  ,  0.36,  1.  ,  0.82],
       [ 0.3 ,  0.  ,  0.  ,  0.48,  0.74,  0.88]]) * 255).astype(np.uint8)

A, B , C, D

In [8]:
from PIL import Image

# Open an image file
image_path = './neitz_common_genes_rdmclr/neitz_common_genes_rdmclr-ocv.png'
image = Image.open(image_path)
A = np.asarray(image)
A

In [ ]:
st = ScreeningTest("govardovskii_common_genes_rdmclr", wavelengths, MandLPeaks, noise_range=[0, 0.05, 0.1], hypercube_sample=0.02, template='govardovskii', randomIndex=True)
st.create_observers_vs_noise()
print(st.metamers_per_observer)
print(st.plate_numbers)

In [ ]:
st = ScreeningTest("stockman_vs_neitz_vs_govardovskii_rdmclr", wavelengths, observers=observers, noise_range=[0, 0.05, 0.1], hypercube_sample=0.02, randomIndex=True)
st.create_observers_vs_noise()

print(st.metamers_per_observer)
print(st.plate_numbers)