In [1]:
import csv
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from chromalab.maxdisplaybasis import *
from chromalab.zonotope import *

In [3]:
%load_ext autoreload
%autoreload 2
%matplotlib ipympl

## Test getLumConstPointsInGamut for 2D

In [4]:
candidate_points = np.eye(2) * 0.5
print("Original Points\n", candidate_points)
zonotope_vecs = np.eye(2) # square
facets = getZonotopeForIntersection(zonotope_vecs, 2)
out = getLumConstPoints(candidate_points, facets)
print("Projected Points\n", out)

Original Points
 [[ 0.5  0. ]
 [ 0.   0.5]]
Projected Points
 [[ 0.5  0. ]
 [ 0.   0.5]]


## Test getLumConstPointsInGamut for 3D

In [9]:
candidate_points = np.eye(3) * 1.5
print("Original Points\n", candidate_points)
zonotope_vecs = np.eye(3) # cube
facets = getZonotopeForIntersection(zonotope_vecs, 3)
out = getLumConstPoints(candidate_points, facets)
print("Projected Points\n", out)

Original Points
 [[ 1.5  0.   0. ]
 [ 0.   1.5  0. ]
 [ 0.   0.   1.5]]
Projected Points
 [[ 1.    0.25  0.25]
 [ 0.25  1.    0.25]
 [ 0.25  0.25  1.  ]]


## Test getLumConstPointsInGamut for 4D

In [7]:
candidate_points = np.eye(4) * 1.1
print("Original Points\n", candidate_points)
zonotope_vecs = np.eye(4) # hypercube
facets = getZonotopeForIntersection(zonotope_vecs, 4)
out = getLumConstPoints(candidate_points, facets)
print("Projected Points\n", out)

Original Points
 [[ 1.1  0.   0.   0. ]
 [ 0.   1.1  0.   0. ]
 [ 0.   0.   1.1  0. ]
 [ 0.   0.   0.   1.1]]
Projected Points
 [[ 1.          0.03333333  0.03333333  0.03333333]
 [ 0.03333333  1.          0.03333333  0.03333333]
 [ 0.03333333  0.03333333  1.          0.03333333]
 [ 0.03333333  0.03333333  0.03333333  1.        ]]
