In [47]:
import csv
import numpy as np
from spectra import Spectra, Pigment
import matplotlib.pyplot as plt
import numpy.typing as npt
import torch as th

In [48]:
wavelengths1 = np.arange(390, 701, 1)
wavelengths10 = np.arange(400, 701, 10)

In [49]:
from observer import Observer, Cone
from inks import Neugebauer, InkGamut, CellNeugebauer
from spectra import Spectra, Pigment, Illuminant

In [50]:
cijk = {}
with open(f'010624.csv') as csvf:
    spamreader = csv.reader(csvf, delimiter=';')
    for i, row in enumerate(spamreader):
        if i < 4: continue
        if row[2] != "CIJK": continue
            
        name = row[4]
        color_data = np.array(row[33:],dtype=float)
        spectra = Spectra(data=color_data, wavelengths=wavelengths10)

        cijk[name] = spectra

In [51]:
d65 = Illuminant.get("D65")

In [52]:
cijk_neug = CellNeugebauer(cijk)
cijk_gamut_d65 = InkGamut(cijk_neug, illuminant=d65)  

In [53]:
tetrachromat_d65 = Observer.tetrachromat(illuminant=d65)

## As usual, lets do Q-axis confusion points

In [55]:
cijk_gamut_d65_buckets05 = cijk_gamut_d65.get_buckets(tetrachromat_d65, save="cijk_gamut_d65_02", stepsize=0.02)

[ 5.28436807  8.21626942  8.00093046  9.58828847]


Generating Point Cloud: 100%|███████████| 6765201/6765201 [02:03<00:00, 54898.63it/s]


Point cloud generated.
Point cloud saved to cijk_gamut_d65_02_point_cloud2.


In [9]:
for d, (a,b) in cijk_gamut_d65_buckets05[:14]:
    print(round(d,4), end=",\t")
    print([f'{round(1000 * _a) / 10:04.1f}' for _a in a], end=",\t")
    print([f'{round(1000 * _b) / 10:04.1f}' for _b in b])

0.0399,	['00.0', '00.0', '65.0', '100.0'],	['25.0', '100.0', '00.0', '50.0']
0.0384,	['00.0', '05.0', '55.0', '95.0'],	['20.0', '95.0', '00.0', '45.0']
0.0381,	['00.0', '00.0', '60.0', '80.0'],	['25.0', '85.0', '00.0', '25.0']
0.0379,	['00.0', '10.0', '55.0', '80.0'],	['20.0', '90.0', '00.0', '15.0']
0.0373,	['00.0', '00.0', '65.0', '90.0'],	['25.0', '100.0', '00.0', '00.0']
0.037,	['00.0', '15.0', '55.0', '95.0'],	['20.0', '100.0', '00.0', '40.0']
0.0365,	['00.0', '10.0', '60.0', '75.0'],	['20.0', '90.0', '05.0', '00.0']
0.0363,	['05.0', '10.0', '55.0', '90.0'],	['25.0', '90.0', '00.0', '50.0']
0.0361,	['00.0', '15.0', '60.0', '85.0'],	['25.0', '95.0', '00.0', '10.0']
0.0361,	['00.0', '00.0', '60.0', '90.0'],	['20.0', '90.0', '05.0', '45.0']
0.036,	['05.0', '00.0', '55.0', '90.0'],	['25.0', '85.0', '00.0', '55.0']
0.0356,	['00.0', '05.0', '65.0', '80.0'],	['25.0', '90.0', '05.0', '10.0']
0.0355,	['00.0', '10.0', '55.0', '85.0'],	['20.0', '95.0', '00.0', '05.0']
0.0354,	['05.0', '00.0'

In [10]:
cijk_gamut_d65_buckets10 = cijk_gamut_d65.get_buckets(tetrachromat_d65, stepsize=0.1)

[ 5.28436807  8.21626942  8.00093046  9.58828847]


Generating Point Cloud: 100%|███████████████| 14641/14641 [00:00<00:00, 52095.75it/s]


Point cloud generated.


In [11]:
for d, (a,b) in cijk_gamut_d65_buckets10[:9]:
    print(round(d,4), end=",\t")
    print([f'{round(1000 * _a) / 10:04.1f}' for _a in a], end=",\t")
    print([f'{round(1000 * _b) / 10:04.1f}' for _b in b])

0.0292,	['20.0', '20.0', '60.0', '100.0'],	['40.0', '100.0', '00.0', '70.0']
0.0292,	['20.0', '00.0', '80.0', '100.0'],	['40.0', '100.0', '10.0', '40.0']
0.0292,	['00.0', '00.0', '60.0', '80.0'],	['20.0', '80.0', '10.0', '40.0']
0.0284,	['00.0', '00.0', '50.0', '70.0'],	['20.0', '70.0', '00.0', '30.0']
0.028,	['30.0', '30.0', '70.0', '90.0'],	['50.0', '100.0', '00.0', '20.0']
0.0276,	['00.0', '10.0', '50.0', '100.0'],	['20.0', '90.0', '00.0', '80.0']
0.0275,	['10.0', '10.0', '70.0', '100.0'],	['30.0', '100.0', '10.0', '50.0']
0.0275,	['30.0', '10.0', '60.0', '80.0'],	['50.0', '80.0', '00.0', '50.0']
0.0274,	['20.0', '00.0', '60.0', '70.0'],	['40.0', '80.0', '00.0', '10.0']


## M-axis

In [12]:
cijk_gamut_d65_buckets05_m_cone = cijk_gamut_d65.get_buckets(tetrachromat_d65, stepsize=0.05, axis=1)

[ 5.28436807  8.21626942  8.00093046  9.58828847]


Generating Point Cloud: 100%|█████████████| 194481/194481 [00:03<00:00, 56540.78it/s]


Point cloud generated.


In [29]:
m_confusion_points = []

In [30]:
for d, (a,b) in cijk_gamut_d65_buckets05_m_cone[:14]:
    print(round(d,4), end=",\t")
    m_confusion_points.append([int(100*x) for x in a])
    m_confusion_points.append([int(100*x) for x in b])
    print([f'{round(1000 * _a) / 10:04.1f}' for _a in a], end=",\t")
    print([f'{round(1000 * _b) / 10:04.1f}' for _b in b])

0.0759,	['05.0', '100.0', '00.0', '00.0'],	['05.0', '00.0', '20.0', '90.0']
0.0754,	['00.0', '100.0', '00.0', '15.0'],	['00.0', '00.0', '15.0', '95.0']
0.075,	['00.0', '100.0', '05.0', '00.0'],	['00.0', '00.0', '25.0', '90.0']
0.0703,	['05.0', '75.0', '00.0', '10.0'],	['05.0', '00.0', '20.0', '70.0']
0.0694,	['00.0', '100.0', '00.0', '25.0'],	['00.0', '05.0', '15.0', '95.0']
0.0692,	['10.0', '85.0', '00.0', '00.0'],	['10.0', '00.0', '25.0', '75.0']
0.0691,	['00.0', '100.0', '00.0', '50.0'],	['00.0', '00.0', '15.0', '100.0']
0.0691,	['05.0', '90.0', '00.0', '15.0'],	['05.0', '00.0', '20.0', '85.0']
0.0689,	['05.0', '95.0', '00.0', '00.0'],	['05.0', '05.0', '20.0', '85.0']
0.068,	['15.0', '90.0', '05.0', '20.0'],	['20.0', '00.0', '25.0', '85.0']
0.0678,	['05.0', '100.0', '05.0', '20.0'],	['05.0', '00.0', '25.0', '95.0']
0.0674,	['00.0', '95.0', '05.0', '00.0'],	['00.0', '05.0', '25.0', '85.0']
0.0674,	['10.0', '90.0', '10.0', '25.0'],	['15.0', '00.0', '30.0', '85.0']
0.0673,	['05.0', '10

In [22]:
cijk_gamut_d65_buckets10_m_cone = cijk_gamut_d65.get_buckets(tetrachromat_d65, stepsize=0.1, axis=1)

[ 5.28436807  8.21626942  8.00093046  9.58828847]


Generating Point Cloud: 100%|███████████████| 14641/14641 [00:00<00:00, 49549.52it/s]


Point cloud generated.


In [31]:
for d, (a,b) in cijk_gamut_d65_buckets10_m_cone[:9]:
    print(round(d,4), end=",\t")
    m_confusion_points.append([int(100*x) for x in a])
    m_confusion_points.append([int(100*x) for x in b])
    print([f'{round(1000 * _a) / 10:04.1f}' for _a in a], end=",\t")
    print([f'{round(1000 * _b) / 10:04.1f}' for _b in b])

0.0654,	['10.0', '100.0', '00.0', '10.0'],	['10.0', '10.0', '20.0', '90.0']
0.0631,	['10.0', '70.0', '00.0', '30.0'],	['10.0', '00.0', '20.0', '70.0']
0.0587,	['20.0', '100.0', '00.0', '00.0'],	['20.0', '00.0', '30.0', '90.0']
0.0574,	['20.0', '80.0', '00.0', '00.0'],	['20.0', '00.0', '30.0', '70.0']
0.0565,	['00.0', '80.0', '10.0', '00.0'],	['00.0', '10.0', '30.0', '70.0']
0.0563,	['10.0', '70.0', '00.0', '00.0'],	['10.0', '10.0', '20.0', '60.0']
0.0556,	['00.0', '70.0', '10.0', '30.0'],	['00.0', '00.0', '30.0', '70.0']
0.0528,	['20.0', '80.0', '00.0', '40.0'],	['20.0', '10.0', '20.0', '80.0']
0.0528,	['20.0', '90.0', '00.0', '80.0'],	['20.0', '00.0', '20.0', '100.0']


In [33]:
len(m_confusion_points)

46

In [34]:
m_confusion_points

[[5, 100, 0, 0],
 [5, 0, 20, 90],
 [0, 100, 0, 15],
 [0, 0, 15, 95],
 [0, 100, 5, 0],
 [0, 0, 25, 90],
 [5, 75, 0, 10],
 [5, 0, 20, 70],
 [0, 100, 0, 25],
 [0, 5, 15, 95],
 [10, 85, 0, 0],
 [10, 0, 25, 75],
 [0, 100, 0, 50],
 [0, 0, 15, 100],
 [5, 90, 0, 15],
 [5, 0, 20, 85],
 [5, 95, 0, 0],
 [5, 5, 20, 85],
 [15, 90, 5, 20],
 [20, 0, 25, 85],
 [5, 100, 5, 20],
 [5, 0, 25, 95],
 [0, 95, 5, 0],
 [0, 5, 25, 85],
 [10, 90, 10, 25],
 [15, 0, 30, 85],
 [5, 100, 0, 5],
 [5, 15, 15, 90],
 [10, 100, 0, 10],
 [10, 10, 20, 90],
 [10, 70, 0, 30],
 [10, 0, 20, 70],
 [20, 100, 0, 0],
 [20, 0, 30, 90],
 [20, 80, 0, 0],
 [20, 0, 30, 70],
 [0, 80, 10, 0],
 [0, 10, 30, 70],
 [10, 70, 0, 0],
 [10, 10, 20, 60],
 [0, 70, 10, 30],
 [0, 0, 30, 70],
 [20, 80, 0, 40],
 [20, 10, 20, 80],
 [20, 90, 0, 80],
 [20, 0, 20, 100]]

## L-Axis

In [35]:
cijk_gamut_d65_buckets05_l_cone = cijk_gamut_d65.get_buckets(tetrachromat_d65, stepsize=0.05, axis=3)

[ 5.28436807  8.21626942  8.00093046  9.58828847]


Generating Point Cloud: 100%|█████████████| 194481/194481 [00:03<00:00, 54312.81it/s]


Point cloud generated.


In [36]:
cijk_gamut_d65_buckets10_l_cone = cijk_gamut_d65.get_buckets(tetrachromat_d65, stepsize=0.1, axis=3)

[ 5.28436807  8.21626942  8.00093046  9.58828847]


Generating Point Cloud: 100%|███████████████| 14641/14641 [00:00<00:00, 50264.06it/s]


Point cloud generated.


In [37]:
l_confusion_points = []

In [41]:
for d, (a,b) in cijk_gamut_d65_buckets05_l_cone[:14]:
    print(round(d,4), end=",\t")
    l_confusion_points.append([int(100*x) for x in a])
    l_confusion_points.append([int(100*x) for x in b])
    print([f'{round(1000 * _a) / 10:04.1f}' for _a in a], end=",\t")
    print([f'{round(1000 * _b) / 10:04.1f}' for _b in b])

0.0744,	['70.0', '85.0', '00.0', '20.0'],	['00.0', '00.0', '90.0', '75.0']
0.0726,	['70.0', '85.0', '00.0', '15.0'],	['00.0', '40.0', '85.0', '65.0']
0.0723,	['75.0', '90.0', '00.0', '40.0'],	['00.0', '05.0', '100.0', '90.0']
0.0716,	['70.0', '85.0', '00.0', '55.0'],	['00.0', '15.0', '90.0', '90.0']
0.0715,	['65.0', '80.0', '00.0', '45.0'],	['00.0', '00.0', '85.0', '80.0']
0.0711,	['75.0', '90.0', '00.0', '35.0'],	['00.0', '00.0', '100.0', '85.0']
0.071,	['75.0', '85.0', '00.0', '70.0'],	['00.0', '05.0', '100.0', '100.0']
0.07,	['70.0', '85.0', '05.0', '45.0'],	['00.0', '05.0', '95.0', '85.0']
0.0696,	['70.0', '95.0', '05.0', '05.0'],	['00.0', '20.0', '95.0', '80.0']
0.0694,	['70.0', '90.0', '15.0', '15.0'],	['00.0', '00.0', '100.0', '75.0']
0.0693,	['75.0', '95.0', '05.0', '30.0'],	['00.0', '20.0', '100.0', '85.0']
0.0692,	['70.0', '85.0', '05.0', '40.0'],	['00.0', '00.0', '95.0', '80.0']
0.069,	['70.0', '75.0', '00.0', '70.0'],	['05.0', '10.0', '85.0', '95.0']
0.0689,	['65.0', '95.0'

In [46]:
for d, (a,b) in cijk_gamut_d65_buckets10_l_cone[:9]:
    print(tetrachromat_d65.observe(cijk_gamut_d65.get_spectra(a)))
    print(tetrachromat_d65.observe(cijk_gamut_d65.get_spectra(b)))

    print(round(d,4), end=",\t")
    l_confusion_points.append([int(100*x) for x in a])
    l_confusion_points.append([int(100*x) for x in b])
    print([f'{round(1000 * _a) / 10:04.1f}' for _a in a], end=",\t")
    print([f'{round(1000 * _b) / 10:04.1f}' for _b in b])
    break

[ 0.18207242  0.20474878  0.22951306  0.24212171]
[ 0.18242458  0.19721503  0.23589033  0.30864717]
0.0658,	['70.0', '90.0', '00.0', '30.0'],	['00.0', '30.0', '90.0', '80.0']


In [43]:
len(l_confusion_points)

46

In [44]:
l_confusion_points

[[70, 85, 0, 20],
 [0, 0, 90, 75],
 [70, 85, 0, 15],
 [0, 40, 85, 65],
 [75, 90, 0, 40],
 [0, 5, 100, 90],
 [70, 85, 0, 55],
 [0, 15, 90, 90],
 [65, 80, 0, 45],
 [0, 0, 85, 80],
 [75, 90, 0, 35],
 [0, 0, 100, 85],
 [75, 85, 0, 70],
 [0, 5, 100, 100],
 [70, 85, 5, 45],
 [0, 5, 95, 85],
 [70, 95, 5, 5],
 [0, 20, 95, 80],
 [70, 90, 15, 15],
 [0, 0, 100, 75],
 [75, 95, 5, 30],
 [0, 20, 100, 85],
 [70, 85, 5, 40],
 [0, 0, 95, 80],
 [70, 75, 0, 70],
 [5, 10, 85, 95],
 [65, 95, 0, 15],
 [0, 10, 90, 85],
 [70, 90, 0, 30],
 [0, 30, 90, 80],
 [70, 100, 0, 10],
 [0, 10, 100, 90],
 [60, 80, 20, 50],
 [0, 10, 90, 80],
 [70, 90, 10, 60],
 [0, 20, 100, 100],
 [60, 90, 30, 30],
 [0, 10, 100, 80],
 [50, 100, 10, 10],
 [0, 0, 90, 90],
 [60, 60, 10, 40],
 [10, 10, 70, 60],
 [60, 90, 0, 40],
 [0, 40, 80, 80],
 [60, 100, 10, 40],
 [0, 10, 100, 100]]