In [1]:
import csv
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
from colour import wavelength_to_XYZ

In [102]:
from chromalab.observer import Observer, Cone, getsRGBfromWavelength, transformToDisplayChromaticity
from chromalab.led import LEDSequence, LEDS

In [5]:
%load_ext autoreload
%autoreload 2
%matplotlib ipympl

In [7]:
tet = LEDSequence.TetrachromaticDisplay()

In [99]:
seq = tet.encode_intensities_to_seq(np.array([[0.5, 0.25, 0.5, 0.5], [0.5, 0.5, 0.5, 0.5]]))
print(seq)

[[ 11 255 255]
 [ 15 255 255]]


In [100]:
tet.decode_seq_to_intensities(seq)

array([[ 0.49206349,  0.23809524,  0.49206349,  0.49206349],
       [ 0.49206349,  0.49206349,  0.49206349,  0.49206349]])

In [105]:
six_prim = LEDSequence(leds=[LEDS.RED, LEDS.GREEN, LEDS.BLUE, LEDS.CYAN, LEDS.YELLOW, LEDS.SBLUE], sequence=[LEDS.RED, LEDS.GREEN, LEDS.BLUE, LEDS.CYAN, LEDS.YELLOW, LEDS.SBLUE] * 4)

In [136]:
intensities = np.array([[0.3, 0.5, 0.8, 0.1, 0.2, 1], [0.7, 0.9, 0.4, 0.2, 0.3, 0.4]])
# intensities = np.ones((2, 6)) * 0.8
encoded = six_prim.encode_intensities_to_seq(intensities)
print(encoded)
decoded = six_prim.decode_seq_to_intensities(encoded)
print(decoded)

[[ 39 149  87]
 [193 218 210]]
[[ 0.26666667  0.46666667  0.8         0.06666667  0.2         1.        ]
 [ 0.66666667  0.86666667  0.4         0.2         0.26666667  0.4       ]]
