In [1]:
import csv
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
from colour import wavelength_to_XYZ

In [2]:
from chromalab.observer import Observer, Cone, getsRGBfromWavelength, transformToDisplayChromaticity
from chromalab.led import LEDSequence

In [5]:
%load_ext autoreload
%autoreload 2
%matplotlib ipympl

In [7]:
tet = LEDSequence.TetrachromaticDisplay()

In [63]:
seq = tet.encode_intensities_to_seq(np.array([0.5, 0.5, 0.5, 0.5]))

[[31 31 31 31]]
[[0 0 0 1 1 1 1 1]
 [0 0 0 1 1 1 1 1]
 [0 0 0 1 1 1 1 1]
 [0 0 0 1 1 1 1 1]]
[[False False False False  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]]


In [73]:
tet.decode_seq_to_intensities(seq)

[[False False False  True  True  True  True  True]
 [False False False  True  True  True  True  True]
 [False False False  True  True  True  True  True]
 [False False False  True  True  True  True  True]]
[[31]
 [31]
 [31]
 [31]]


array([[ 0.49206349],
       [ 0.49206349],
       [ 0.49206349],
       [ 0.49206349]])