In [143]:
%load_ext autoreload
%autoreload 2
from chromalab.printer import Printer, PrinterMapper
import numpy as np
import random
from PIL import Image, ImageDraw

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [5]:
# Printers are based on a mapping of the 6d ink coordinates to which printer/channel they're pringing out of,
# the function should take a 6-tuple, and return a list of N 4-tuples, where N is the number of prints you want.
# the order in each tuple is the CMYK channels of each printer (i.e. the 4th channel should always be a 0)
# for example, if I have a printer that prints Violet in the M channel, another that prints Turquoise, Red, and Citrus in the CMY channels,
# and a third printer that prints Blue and Maskara in the M and Y channels. Then to avoid accidental K printing I need to split up that
# second printer, so I can print the C (turquoise) and MY (Red,Citrus) seperately, and I can make functions like this:
def ExamplePrinterMap(c):
        return [(0,c[0],0,0),
                (c[1],0,0,0),
                (0,c[2],c[3],0),
                (0,c[4],c[5],0)]

examplePrinterNames = ["V","T","RC","BM"] # violet turquise red citrus blue maskara

# the printer names should be a list of length N, and correspond to the names of the .tif files that get created, so they should remind you which printer they are required for.
# here, T and RC come out of the same printer, but since the physical printer is labeled with these names I can still figure it out.
# examplePrinterNames = ["P2", "P1", "P1", "P3"] would also work, whatever makes more sense to you

In [6]:
#to make isochromatic dot test, do something like this
p = Printer() #the important thing is for the directory file to have your secretimages/ file in it

testDict = {
    "A": ([25,32,47,85],[37,90,2,50],'87'), #downstairs
    "B": ([27,2,57,85],[42,95,2,17],'85'),
    "C": ([30,22,50,90],[42,95,0,52],'73'),
    "D": ([30,25,47,90],[37,90,2,50],'27'), #2850k
    "E": ([27,15,52,82],[40,87,0,25],'39'),
    "F": ([30,7,52,95],[40,97,0,50],'68'),
    "G": ([30,17,50,92],[37,90,2,62],'96'), #4800k
    "H": ([30,17,50,92],[37,92,2,65],'72'),
    "I": ([32,17,50,80],[40,87,0,25],'35'),
    "J": ([30,17,50,92],[37,90,2,62],'67'), #6500k
    "K": ([30,22,50,90],[37,90,2,50],'64'),
    "L": ([27,7,55,85],[40,87,0,45],'89'),
}

for t in testDict.keys():
    inside,outside,secret = testDict[t]
    print(inside)
    inside = p.CIJKtoCMYIJK(p.div100(inside)) #if the printer values are out of 1, or are 6d, you can skip those steps
    outside = p.CIJKtoCMYIJK(p.div100(outside))
    p.generate_CC(inside,outside,0,secret,t,True)



[25, 32, 47, 85]
18
24
20
25
18
24
24
24
14
24
13
25
12
24
12
25
20
26
20
13
19
20
12
24
14
20
13
25
13
26
20
24
19
18
12
18
25
20
13
13
25
24
24
12
20
26
20
14
13
12
18
19
19
12
12
20
26
25
18
24
14
20
24
25
20
12
25
24
18
24
25
13
18
24
25
18
24
25
26
19
26
20
19
14
24
25
26
14
13
25
18
20
19
14
20
20
19
18
26
13
20
18
26
12
13
13
19
20
24
14
24
19
14
25
19
12
24
12
20
25
14
18
18
24
13
13
12
13
25
14
14
18
18
19
14
20
24
14
19
26
14
24
14
12
24
20
18
25
24
24
26
20
24
18
24
19
26
19
14
14
13
25
26
14
13
13
14
25
24
20
25
24
14
20
13
12
19
13
24
25
20
12
13
19
25
26
26
12
12
26
24
26
26
13
24
19
14
12
25
26
14
19
13
13
18
24
19
19
26
24
19
12
12
18
14
19
25
19
20
26
26
19
12
26
24
26
20
20
25
20
13
14
14
12
14
20
18
14
13
20
13
20
25
14
12
20
19
26
14
14
19
13
20
26
20
24
12
14
14
26
26
18
13
13
19
26
18
25
12
20
26
13
14
13
12
26
13
13
26
18
18
24
26
14
18
20
24
19
13
18
14
12
14
25
13
20
18
20
24
24
13
12
25
25
20
13
13
13
18
14
18
19
24
19
20
19
19
19
18
19
13
25
25
25
19
24
26
20

In [7]:
# to generate a dot list, do something like this
p = Printer(printerMap= Printer.SixInkPrinterMap, printerNames=Printer.sixInkPrinterNames)
l=[]
for c in range(2):
    for m in range(2):
        for y in range(2):
            for i in range(2):
                for j in range(2):
                    for k in range(2):
                        l += [[c,m,y,i,j,k]]
p.generateDotList(l) #this generates the NB primaries for 6 inks

[0, 0, 0, 0, 0, 0]
colors= [(0, 0, 0, 0), (0, 0, 0, 0), (0, 0, 0, 0), (0, 0, 0, 0)]
[0, 0, 0, 0, 0, 1]
colors= [(0, 0, 0, 0), (0, 0, 0, 0), (0, 0, 0, 0), (0, 0, 255, 0)]
[0, 0, 0, 0, 1, 0]
colors= [(0, 0, 0, 0), (0, 0, 0, 0), (0, 0, 0, 0), (0, 255, 0, 0)]
[0, 0, 0, 0, 1, 1]
colors= [(0, 0, 0, 0), (0, 0, 0, 0), (0, 0, 0, 0), (0, 255, 255, 0)]
[0, 0, 0, 1, 0, 0]
colors= [(0, 0, 0, 0), (0, 0, 0, 0), (0, 0, 255, 0), (0, 0, 0, 0)]
[0, 0, 0, 1, 0, 1]
colors= [(0, 0, 0, 0), (0, 0, 0, 0), (0, 0, 255, 0), (0, 0, 255, 0)]
[0, 0, 0, 1, 1, 0]
colors= [(0, 0, 0, 0), (0, 0, 0, 0), (0, 0, 255, 0), (0, 255, 0, 0)]
[0, 0, 0, 1, 1, 1]
colors= [(0, 0, 0, 0), (0, 0, 0, 0), (0, 0, 255, 0), (0, 255, 255, 0)]
[0, 0, 1, 0, 0, 0]
colors= [(0, 0, 0, 0), (0, 0, 0, 0), (0, 255, 0, 0), (0, 0, 0, 0)]
[0, 0, 1, 0, 0, 1]
colors= [(0, 0, 0, 0), (0, 0, 0, 0), (0, 255, 0, 0), (0, 0, 255, 0)]
[0, 0, 1, 0, 1, 0]
colors= [(0, 0, 0, 0), (0, 0, 0, 0), (0, 255, 0, 0), (0, 255, 0, 0)]
[0, 0, 1, 0, 1, 1]
colors= [(0, 0, 0, 0), 

In [18]:
# def BackupPrinterMap(c):
#     return [(c[0],c[1],0,0),
#             (c[2],0,c[3],0),
#             (0,0,c[4],0)]
# backupPrinterNames = ["PV","TC","M"]

def BackupPrinterMap(c):
    return [(0,c[1],0,0),
            (c[2],0,c[3],0),
            (0,c[0],0,0),
            (0,0,c[4],0)]
backupPrinterNames = ["V","TC","R","M"]

p = Printer(printerMap=BackupPrinterMap, printerNames=backupPrinterNames)
l=[]
for c in range(2):
    for m in range(2):
        for y in range(2):
            for i in range(2):
                for j in range(2):
                    l += [[c,m,y,i,j]]
p.generateDotList(l,name="withLamy") #this generates the NB primaries for 6 inks


[0, 0, 0, 0, 0]
colors= [(0, 0, 0, 0), (0, 0, 0, 0), (0, 0, 0, 0), (0, 0, 0, 0)]
[0, 0, 0, 0, 1]
colors= [(0, 0, 0, 0), (0, 0, 0, 0), (0, 0, 0, 0), (0, 0, 255, 0)]
[0, 0, 0, 1, 0]
colors= [(0, 0, 0, 0), (0, 0, 255, 0), (0, 0, 0, 0), (0, 0, 0, 0)]
[0, 0, 0, 1, 1]
colors= [(0, 0, 0, 0), (0, 0, 255, 0), (0, 0, 0, 0), (0, 0, 255, 0)]
[0, 0, 1, 0, 0]
colors= [(0, 0, 0, 0), (255, 0, 0, 0), (0, 0, 0, 0), (0, 0, 0, 0)]
[0, 0, 1, 0, 1]
colors= [(0, 0, 0, 0), (255, 0, 0, 0), (0, 0, 0, 0), (0, 0, 255, 0)]
[0, 0, 1, 1, 0]
colors= [(0, 0, 0, 0), (255, 0, 255, 0), (0, 0, 0, 0), (0, 0, 0, 0)]
[0, 0, 1, 1, 1]
colors= [(0, 0, 0, 0), (255, 0, 255, 0), (0, 0, 0, 0), (0, 0, 255, 0)]
[0, 1, 0, 0, 0]
colors= [(0, 255, 0, 0), (0, 0, 0, 0), (0, 0, 0, 0), (0, 0, 0, 0)]
[0, 1, 0, 0, 1]
colors= [(0, 255, 0, 0), (0, 0, 0, 0), (0, 0, 0, 0), (0, 0, 255, 0)]
[0, 1, 0, 1, 0]
colors= [(0, 255, 0, 0), (0, 0, 255, 0), (0, 0, 0, 0), (0, 0, 0, 0)]
[0, 1, 0, 1, 1]
colors= [(0, 255, 0, 0), (0, 0, 255, 0), (0, 0, 0, 0), (0, 

In [130]:
cl=[]
for c in range(3):
    for m in range(3):
        for y in range(3):
            for i in range(3):
                for j in range(3):
                    cl += [[c,m,y,i,j]]
cl = [[x/2 for x in c] for c in cl]
p.generateMultiPageDotList(cl,name="withlamycellular",perPage=72)
p.generateDotList(cl,name="withLamyCellular")

!
!!
[0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.5]
[0.0, 0.0, 0.0, 0.0, 1.0]
[0.0, 0.0, 0.0, 0.5, 0.0]
[0.0, 0.0, 0.0, 0.5, 0.5]
[0.0, 0.0, 0.0, 0.5, 1.0]
[0.0, 0.0, 0.0, 1.0, 0.0]
[0.0, 0.0, 0.0, 1.0, 0.5]
[0.0, 0.0, 0.0, 1.0, 1.0]
[0.0, 0.0, 0.5, 0.0, 0.0]
[0.0, 0.0, 0.5, 0.0, 0.5]
[0.0, 0.0, 0.5, 0.0, 1.0]
[0.0, 0.0, 0.5, 0.5, 0.0]
[0.0, 0.0, 0.5, 0.5, 0.5]
[0.0, 0.0, 0.5, 0.5, 1.0]
[0.0, 0.0, 0.5, 1.0, 0.0]
[0.0, 0.0, 0.5, 1.0, 0.5]
[0.0, 0.0, 0.5, 1.0, 1.0]
[0.0, 0.0, 1.0, 0.0, 0.0]
[0.0, 0.0, 1.0, 0.0, 0.5]
[0.0, 0.0, 1.0, 0.0, 1.0]
[0.0, 0.0, 1.0, 0.5, 0.0]
[0.0, 0.0, 1.0, 0.5, 0.5]
[0.0, 0.0, 1.0, 0.5, 1.0]
[0.0, 0.0, 1.0, 1.0, 0.0]
[0.0, 0.0, 1.0, 1.0, 0.5]
[0.0, 0.0, 1.0, 1.0, 1.0]
[0.0, 0.5, 0.0, 0.0, 0.0]
[0.0, 0.5, 0.0, 0.0, 0.5]
[0.0, 0.5, 0.0, 0.0, 1.0]
[0.0, 0.5, 0.0, 0.5, 0.0]
[0.0, 0.5, 0.0, 0.5, 0.5]
[0.0, 0.5, 0.0, 0.5, 1.0]
[0.0, 0.5, 0.0, 1.0, 0.0]
[0.0, 0.5, 0.0, 1.0, 0.5]
[0.0, 0.5, 0.0, 1.0, 1.0]
[0.0, 0.5, 0.5, 0.0, 0.0]
[0.0, 0.5, 0.5, 0.0, 0.5]
[0.0, 0

In [111]:
swaps = []
for i in range(81):
    if random.random() < 0.15:
        swaps += [i]
print(swaps)

[11, 12, 16, 18, 24, 30, 36, 40, 46, 47, 52, 58, 63, 66, 68, 69, 76, 80]


In [141]:
%load_ext autoreload
%autoreload 2
# file_path = "/Users/frackfrick/Desktop/SchoolStuff/compColor/25lamy_percentages.npy"
file_path = "../data/nix/9x9_grey_percentages.npy"
# backup_path = "../data/nix/5x5_full_percentages.npy"
# index_path = "/Users/frackfrick/Desktop/SchoolStuff/Research/9x9_idx_into_cubemap.npy"
index_path = "../data/nix/9x9_idx_into_cubemap.npy"


data = np.load(file_path)
index = np.load(index_path)
# backup = np.load(backup_path)
def BackupPrinterMap(c):
    return [(0,c[1],0,0),
            (c[2],0,c[3],0),
            (0,c[0],0,0),
            (0,0,c[4],0)]
backupPrinterNames = ["V","TC","R","M"]

p = Printer(printerMap=BackupPrinterMap, printerNames=backupPrinterNames)
p.newGeneralGrid(index,data,"9x9grey",30,10)
# p.newGeneralGrid(index,data,"5x5grey",55,20)
# p.newGeneralGrid(index,data,"3x3labels",55,20,labels=True)
# p.new9x9Shuffle(index,data)
# print(swaps)
# p.new9x9Shuffle(index,data,swaps,"swapsBackup",backupData=backup)
# p.new9x9Shuffle(index,data,[],"swapsBackupNone",backupData=backup)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing NAN
printing 9x9grey/0


printing swapsNone/0


In [124]:
sw = [11, 12, 16, 18, 24, 30, 36, 40, 46, 47, 52, 58, 63, 66, 68, 69, 76, 80]
sw = [(x//9,x%9) for x in sw]
print(sw)

[(1, 2), (1, 3), (1, 7), (2, 0), (2, 6), (3, 3), (4, 0), (4, 4), (5, 1), (5, 2), (5, 7), (6, 4), (7, 0), (7, 3), (7, 5), (7, 6), (8, 4), (8, 8)]


In [108]:
%load_ext autoreload
%autoreload 2
file_path = "../data/nix/3x3_full_percentages.npy"
data = np.load(file_path)
colors = []
labels = []
for face in range(len(data)):
    for i in range(len(data[face])):
        colors += [data[face][i]]
        labels += [f"({face},{i})"]
p.generateMultiPageDotList(colors=colors,name="ball3x3",manualDotSize=150,customLabels=labels,perPage=40,rect=True)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
!
!!
[0.15 0.5  0.9  0.35 0.9 ]
colors= [(0, 127, 0, 0), (229, 0, 89, 0), (0, 38, 0, 0), (0, 0, 229, 0)]
[0.5 0.3 1.  0.2 0.5]
colors= [(0, 76, 0, 0), (255, 0, 51, 0), (0, 127, 0, 0), (0, 0, 127, 0)]
[0.55 0.55 0.85 0.15 0.5 ]
colors= [(0, 140, 0, 0), (216, 0, 38, 0), (0, 140, 0, 0), (0, 0, 127, 0)]
[0.55 0.05 0.95 0.35 0.4 ]
colors= [(0, 12, 0, 0), (242, 0, 89, 0), (0, 140, 0, 0), (0, 0, 102, 0)]
[0.7  0.15 0.9  0.2  0.8 ]
colors= [(0, 38, 0, 0), (229, 0, 51, 0), (0, 178, 0, 0), (0, 0, 204, 0)]
[0.85 0.25 0.85 0.1  0.25]
colors= [(0, 63, 0, 0), (216, 0, 25, 0), (0, 216, 0, 0), (0, 0, 63, 0)]
[0.5  0.3  0.7  0.45 0.55]
colors= [(0, 76, 0, 0), (178, 0, 114, 0), (0, 127, 0, 0), (0, 0, 140, 0)]
[0.75 0.25 0.65 0.3  1.  ]
colors= [(0, 63, 0, 0), (165, 0, 76, 0), (0, 191, 0, 0), (0, 0, 255, 0)]
[0.85 0.4  0.65 0.2  0.25]
colors= [(0, 102, 0, 0), (165, 0, 51, 0), (0, 216, 0, 0), (0, 0, 63, 0)]
[0.1  0.85 

In [127]:
l= [[30,100,20,60,5],[100,30,25,15,100],
    [25,90,5,60,0],[95,0,30,15,75],
    [20,85,5,80,10],[90,0,10,60,100],
    [15,100,10,85,25],[100,5,75,65,5],
    [75,75,0,35,15],[100,5,45,5,10],
    [75,70,10,40,0],[100,0,15,10,75],
    [75,70,5,70,0],[100,10,25,55,40],
    [75,70,0,35,0],[100,0,5,0,75]]
l = [[x/100 for x in c] for c in l]
p.generateDotList(l,name="testPairs2")

[0.3, 1.0, 0.2, 0.6, 0.05]
[1.0, 0.3, 0.25, 0.15, 1.0]
[0.25, 0.9, 0.05, 0.6, 0.0]
[0.95, 0.0, 0.3, 0.15, 0.75]
[0.2, 0.85, 0.05, 0.8, 0.1]
[0.9, 0.0, 0.1, 0.6, 1.0]
[0.15, 1.0, 0.1, 0.85, 0.25]
[1.0, 0.05, 0.75, 0.65, 0.05]
[0.75, 0.75, 0.0, 0.35, 0.15]
[1.0, 0.05, 0.45, 0.05, 0.1]
[0.75, 0.7, 0.1, 0.4, 0.0]
[1.0, 0.0, 0.15, 0.1, 0.75]
[0.75, 0.7, 0.05, 0.7, 0.0]
[1.0, 0.1, 0.25, 0.55, 0.4]
[0.75, 0.7, 0.0, 0.35, 0.0]
[1.0, 0.0, 0.05, 0.0, 0.75]
printing testPairs2/


In [ ]:
file_path = "../data/nix/5x5_rgb.npy"
index_path = "../data/nix/5x5_idx_into_cubemap.npy"


data = np.load(file_path)
index = np.load(index_path)
dotSize=55
border=20
r = dotSize/2
size = 1024
sideLen = len(index[0])
im = Image.new('RGB',(int(size*1.3), size))
dr = ImageDraw.Draw(im)
for square in range(6):
    for c in range(sideLen**2):
        ind = index[square][c//sideLen][c%sideLen]
        x = r + ind[0] * (sideLen-1) * (dotSize + border) + 2 * border
        y = r + ind[1] * (sideLen-1) * (dotSize + border) + 2 * border
        y = size - y
        inde = c
        c = data[square][c]
        # print(inde,c[0])
        circle = [x - r, y - r, x + r, y + r]
        # print("circle is",circle)
        dr.ellipse(circle,c)

im.save("./rgb.png")