In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
ink_spectra_points = np.load("ink_spectra_points.npy")

In [4]:
ink_spectra_points.shape

(1331, 31)

In [5]:
tetrachromat_ink_gamut = np.load("tetrachromat_ink_gamut.npy")

In [6]:
tetrachromat_ink_gamut.shape

(1334, 4)

In [8]:
magnitudes = np.linalg.norm(tetrachromat_ink_gamut, axis=1)

# Get the indices of the four largest magnitudes
max_indices = magnitudes.argsort()[-4:][::-1]

# Extract the four points with the largest magnitudes
max_points = tetrachromat_ink_gamut[max_indices]

print(max_points)

[[0.86679532 0.85748026 0.85409703 0.85513736]
 [0.83493805 0.84860348 0.84801181 0.84972018]
 [0.8490446  0.83000849 0.82905767 0.83297054]
 [0.85485178 0.83266103 0.82654045 0.82675362]]
